// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFVRxx1KtUzxdxRohZjuO9Dlvje5f-OVM',
    appId: '1:63758302436:web:42c00bb33f8fbc3ae740f1',
    messagingSenderId: '63758302436',
    projectId: 'lucidly-in',
    authDomain: 'lucidly-in.firebaseapp.com',
    storageBucket: 'lucidly-in.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPpPYuzK25CmZt-yh_mpRzyazlKu5kfjA',
    appId: '1:63758302436:android:4df6dfefe6bffa29e740f1',
    messagingSenderId: '63758302436',
    projectId: 'lucidly-in',
    storageBucket: 'lucidly-in.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZN15gsDFYToKnt3XMjTbzP-Xg50L8ms',
    appId: '1:63758302436:ios:6123250d83c2b6bde740f1',
    messagingSenderId: '63758302436',
    projectId: 'lucidly-in',
    storageBucket: 'lucidly-in.firebasestorage.app',
    iosBundleId: 'com.example.lucidlyIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZN15gsDFYToKnt3XMjTbzP-Xg50L8ms',
    appId: '1:63758302436:ios:6123250d83c2b6bde740f1',
    messagingSenderId: '63758302436',
    projectId: 'lucidly-in',
    storageBucket: 'lucidly-in.firebasestorage.app',
    iosBundleId: 'com.example.lucidlyIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFVRxx1KtUzxdxRohZjuO9Dlvje5f-OVM',
    appId: '1:63758302436:web:54636e52d1ac5ad2e740f1',
    messagingSenderId: '63758302436',
    projectId: 'lucidly-in',
    authDomain: 'lucidly-in.firebaseapp.com',
    storageBucket: 'lucidly-in.firebasestorage.app',
  );

}